# Generated by Django 4.2.10 on 2026-09-27 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('key', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='卡密')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='金额')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.SmallIntegerField(choices=[(0, '未绑定'), (1, '已绑定'), (3, '已失效')], db_index=True, default=0, verbose_name='状态')),
                ('bound_at', models.DateTimeField(blank=True, null=True, verbose_name='绑定时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '卡密',
                'db_table': 'card_key',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='设备账号')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '禁用')], default=0, verbose_name='状态')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近在线时间')),
            ],
            options={
                'verbose_name': '设备',
                'db_table': 'card_device',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('cancel', '取消'), ('bind', '绑定'), ('unbind', '解绑')], max_length=16, verbose_name='动作')),
                ('source', models.CharField(choices=[('admin', '后台'), ('client', '客户端')], max_length=8, verbose_name='来源')),
                ('operator_name', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人名称')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cards.cardkey', verbose_name='卡密')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '卡密日志',
                'db_table': 'card_log',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='cardkey',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.device', verbose_name='绑定设备'),
        ),
    ]
