# Generated by Django 4.2.10 on 2026-09-27 03:12

import apps.ads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='广告位名称')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='唯一编码')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '广告位',
                'db_table': 'ad_slot',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='图片名称')),
                ('subtitle', models.CharField(blank=True, default='', max_length=128, verbose_name='副标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.ads.models.ad_image_path, verbose_name='主图')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=apps.ads.models.ad_image_path, verbose_name='副图')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='跳转链接')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.adslot', verbose_name='所属广告位')),
            ],
            options={
                'verbose_name': '广告图片',
                'db_table': 'ad_image',
                'ordering': ['-id'],
            },
        ),
    ]
