# Generated by Django 4.2.10 on 2026-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, default='', max_length=32, verbose_name='姓名')),
                ('role', models.CharField(choices=[('super', '超级管理员'), ('operator', '运营')], default='operator', max_length=16, verbose_name='角色')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限编码列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'db_table': 'account_user',
                'ordering': ['-id'],
            },
        ),
    ]
