# Generated by Django 4.2.10 on 2026-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64, verbose_name='配置名称')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='唯一编码')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'db_table': 'sys_config',
                'ordering': ['-id'],
            },
        ),
    ]
